use_frameworks!

platform :ios, '8.0'

target 'MMNetworking_Example' do
  pod 'MMNetworking', :path => '../'

  target 'MMNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
